### ISSUE TITLE
Repeated reload display the view source

### ISSUE THREAD

**Issue by zonblade** [zonblade/php-view-source-protection#1]
repeatedly refreshing the view source make view source visible.

**This issue currently on my way to fix it**

**Comment by zonblade** [comment]
still searching for methods, please be patient ;) 

- [ ] finding solution

**Comment by zonblade** [comment]
**RENDER FEATURE ADDED, FIREFOX PROBLEM FIXED**

**Comment by mzayn** [comment]
any latest update for php8? 

how using with chrome ?
